# Generated by Django 5.2.1 on 2025-06-02 23:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubes', '0002_jogador'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jogador',
            options={'verbose_name_plural': 'Jogadores'},
        ),
        migrations.AddField(
            model_name='clube',
            name='data_fundacao',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='clube',
            name='tem_estadio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clube',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
