# Generated by Django 5.2.1 on 2025-06-09 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubes', '0003_alter_jogador_options_clube_data_fundacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='clube',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubes.clube'),
        ),
    ]
