# Generated by Django 5.2.1 on 2025-06-30 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível')),
                ('observacao', models.CharField(blank=True, max_length=500, null=True, verbose_name='Observação')),
            ],
        ),
    ]
